[package]
name = "russimp-ng"
version = "3.2.1"
authors = ["Kek5chen"]
edition = "2021"
license-file = "LICENSE"
readme = "README.md"
homepage = "https://github.com/Kek5chen/russimp-ng"
categories = ["rendering", "external-ffi-bindings", "game-engines", "multimedia"]
keywords = ["assimp", "3d", "blend", "3ds", "glTF"]
repository = "https://github.com/Kek5chen/russimp-ng"
description = "Assimp bindings for rust"
exclude = [ "*.bash", "/models" ]

[lib]
name = "russimp_ng"
path = "src/lib.rs"

[dependencies]
russimp-sys-ng = { git = "https://github.com/Kek5chen/russimp-sys-ng.git" } 
num-derive = "0.4"
num-traits = "0.2"
num_enum = "0.7"
derivative = "2.2.0"
strum = "0.27"
strum_macros = "0.27"
mint = { version = "0.5", optional = true }

[features]
default = ["russimp-sys-ng/build-assimp"]
prebuilt = ["russimp-sys-ng/prebuilt"]
static-link = ["russimp-sys-ng/static-link"]
nozlib = ["russimp-sys-ng/nozlib"]

[package.metadata.docs.rs]
features = ["prebuilt"]
